sonar.projectKey=AlexisYazir_back-sport
sonar.organization=alexisyazir
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**,**/*.spec.ts
sonar.inclusions=src/modules/auth/**,src/modules/products/**,src/modules/inventory/**