# Identificación del proyecto
sonar.projectKey=AlexisYazir_back-sport
sonar.organization=alexisyazir
sonar.host.url=https://sonarcloud.io

# Rutas a analizar
sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**, dist/**, coverage/**

# Lenguaje y configuración
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Módulos a evaluar (según tu plan de pruebas: autenticación, CRUD productos, inventario)
sonar.inclusions=src/modules/auth/**, src/modules/products/**, src/modules/inventory/**