# Identificación del proyecto
sonar.projectKey=AlexisYazir_back-sport
sonar.organization=alexisyazir
sonar.host.url=https://sonarcloud.io

# Código fuente
sonar.sources=src

# Tests
sonar.tests=test

# Exclusiones
sonar.exclusions=node_modules/**,dist/**,coverage/**,**/*.spec.ts

# Módulos a evaluar
sonar.inclusions=src/modules/auth/**,src/modules/products/**,src/modules/inventory/**